[package]
name = "cap_token"
version = "1.0.0"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework/", rev = "main" }
Std = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/stdlib/", rev = "main" }

[addresses]
cap_token = "_" 